# Build stage
FROM golang:1.16.3 AS build-env
ENV GO111MODULE=on
ENV CGO_ENABLED=0

WORKDIR /app/certm
COPY go.mod .
COPY go.sum .

RUN go mod download
COPY . .

RUN go build -o certm
RUN chmod +x certm

# Develop stage
FROM centos:8 AS develop
RUN yum install -y epel-release && yum -y update && yum install -y haproxy
RUN curl -O https://dl.eff.org/certbot-auto && mv certbot-auto /usr/local/bin/certbot-auto && chmod 0755 /usr/local/bin/certbot-auto
WORKDIR /usr/local/bin
COPY --from=build-env /app/certm/certm .
RUN chmod +x certm
ENV WORKDIR "/usr/local/bin"
ENV PATH "${WORKDIR}:${PATH}"

RUN mkdir -p /etc/haproxy/ssl && \
    mkdir -p /etc/letsencrypt/live/example.com && \
    mkdir -p /etc/letsencrypt/live/rishat.space && \
    mkdir -p /etc/letsencrypt/archive/example.com && \
    mkdir -p /etc/letsencrypt/archive/rishat.space

RUN openssl req -x509 -nodes -days 7300 -newkey rsa:2048 -keyout /etc/letsencrypt/archive/example.com/fullchain.pem -out /etc/letsencrypt/archive/example.com/privkey.pem -subj "/C=PE/ST=Lima/L=Lima/O=Acme Inc. /OU=IT Department/CN=acme.com"
RUN openssl req -x509 -nodes -days 7300 -newkey rsa:2048 -keyout /etc/letsencrypt/archive/rishat.space/fullchain.pem -out /etc/letsencrypt/archive/rishat.space/privkey.pem -subj "/C=PE/ST=Lima/L=Lima/O=Acme Inc. /OU=IT Department/CN=acme.com"

RUN ln -s /etc/letsencrypt/archive/example.com/fullchain.pem /etc/letsencrypt/live/example.com/fullchain.pem && \
    ln -s /etc/letsencrypt/archive/example.com/privkey.pem /etc/letsencrypt/live/example.com/privkey.pem && \
    ln -s /etc/letsencrypt/archive/example.com/fullchain.pem /etc/letsencrypt/live/rishat.space/fullchain.pem && \
    ln -s /etc/letsencrypt/archive/example.com/privkey.pem /etc/letsencrypt/live/rishat.space/privkey.pem

CMD ["certm", "--version"]
